CREATE TABLE IF NOT EXISTS requests (
  id TEXT PRIMARY KEY,
  request_id TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  whatsapp TEXT,
  pillar TEXT NOT NULL,
  service TEXT NOT NULL,
  description TEXT NOT NULL,
  budget TEXT,
  deadline TEXT,
  files TEXT DEFAULT '[]',
  source TEXT DEFAULT 'direct',
  source_referral TEXT,
  status TEXT DEFAULT 'New',
  notes TEXT DEFAULT '',
  formspree_id TEXT,
  project_id TEXT,
  ip_hash TEXT,
  CHECK (pillar IN ('assist', 'build', 'iot', 'home')),
  CHECK (status IN ('New', 'Reviewing', 'Accepted', 'In Progress', 'Completed', 'Cancelled'))
);
